sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker

before_install:
    - make docker-build
    - make docker-run
    - docker ps -a

script:
    - curl -L http://127.0.0.1:9123

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push magicmark/personal-website;
    fi
