version: '2'
services:
    personal-website-web:
        build:
            context: .
        restart: always
        environment:
            - VIRTUAL_PORT=9123
            - VIRTUAL_HOST=mark.larah.me,web.local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - web
        labels:
            - "traefik.backend=personal-website"
            - "traefik.frontend.rule=Host:mark.larah.me"
            - "traefik.port=9123"
            - "traefik.protocol=http"

networks:
  web:
    external:
      name: traefik_webgateway
